wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.show-sql=true
